---
- name: Install and configure WordPress
  hosts: wordpress
  become: true
  roles:
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.wordpress
  vars:
    mysql_root_password: "password"
    mysql_databases:
      - name: wordpress
        encoding: utf8mb4
        collation: utf8mb4_unicode_ci
    mysql_users:
      - name: wordpress
        host: "{{ inventory_hostname }}"
        password: "password"
        priv: "wordpress.*:ALL"
    wordpress_db_name: "wordpress"
    wordpress_db_user: "wordpress"
    wordpress_db_password: "password"
    wordpress_db_host: "localhost"
    wordpress_db_prefix: "wp_"
    wordpress_title: "My WordPress Site"
    wordpress_admin_user: "admin"
    wordpress_admin_password: "password"
    wordpress_admin_email: "admin@example.com"
    wordpress_language: "en_US"

